### ISSUE TITLE
Deploy Akash-deploy with Akash-deploy - Errno::ENOTTY (Inappropriate ioctl for device)

### ISSUE THREAD

**Issue by vincentken3d** [tombeynon/akash-deploy#2] opened 2021-04-06 06:15 UTC
This error happen on the wallet import.

![image](https://user-images.githubusercontent.com/63375511/113667049-3a1da880-967e-11eb-87e0-adde2318c104.png)

![image](https://user-images.githubusercontent.com/63375511/113667350-af897900-967e-11eb-9a7a-336b6ca33155.png)

**Comment by vincentken3d** [comment] 2021-04-06 07:32
Here is the url to test the issue yourself -> http://qudn4fag81b8vaiqbgkobtm0c4.ingress.sjc1p0.mainnet.akashian.io/wallet/new

**Comment by tombeynon** [comment] 2021-04-06 08:29
Hi @vincentken3d - strange! I've not seen this error before. I'll have a proper look later today but in the meantime could you let me know:

1. The full `docker run` command you're using
2. If the Akash directory you provided to `docker run` is an existing or new directory/does it have keyfiles already?

I assume you did enter a password in the first field in your screenshot?

**Comment by tombeynon** [comment] 2021-04-06 09:29
Ah this tool is meant to be run on your own machine, _not_ on Akash. If you've only tried running it on Akash then that will likely be the issue. Could you let me know if you've done anything different from the install docs: https://github.com/tombeynon/akash-deploy#installation

**Comment by vincentken3d** [comment] 2021-04-06 13:52
> Ah this tool is meant to be run on your own machine, _not_ on Akash. If you've only tried running it on Akash then that will likely be the issue. Could you let me know if you've done anything different from the install docs: https://github.com/tombeynon/akash-deploy#installation

Would it be possible to make it work on Akash? I basically published your tool with your tool. Pretty cool!

**Comment by tombeynon** [comment] 2021-04-07 09:35
I'm going to close this issue for now as I believe the tool is working as intended. I'll update when I'm further down the road of a hosted solution

**Closed by tombeynon** 2021-04-07 09:35 UTC
